version: 2
jobs:
  build:
    triggers:
      - schedule:
          cron: "0 4 * * 1-5"
          
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Decrypt p12
          command: './cmd/decrypt.sh'
      - run:
          name: Backend Build and Tets
          command: 'mvn verify -Dit'