version: 2
jobs:
  build:
    triggers:
      - schedule:
          cron: "0 4 * * 1-5"
          
    docker:
      - image: circleci/openjdk:8u171-jdk
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Decrypt p12
          command: './cmd/decrypt.sh'
      - run:
          name: Setup custom environment GAPI_SERVICE_ACCOUNT_KEY
          command: export GAPI_SERVICE_ACCOUNT_KEY=$(pwd)/src/main/resources/dexboard-reload-a4ade2e84e5e.p12
      - run:
          name: Print GAPI_SERVICE_ACCOUNT_KEY
          command: 'echo $GAPI_SERVICE_ACCOUNT_KEY'

      - run:
          name: Print GAPI_SERVICE_ACCOUNT_EMAIL
          command: 'echo $GAPI_SERVICE_ACCOUNT_EMAIL'

      - run:
          name: Backend Build and Tets
          command: 'mvn verify -Dit'